#

version: 2
updates:
  # - package-ecosystem: "npm"
  #   directory: "/node-api"
  #   schedule:
  #     interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
